# Generated by Django 3.2.8 on 2021-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dividens_referral_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral_reward',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
