# Generated by Django 3.2.8 on 2021-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_referral_reward_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dividens',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interest',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='min_amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
